[2025-08-28T07:30:34.678+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T07:30:34.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.sales_per_country manual__2025-08-28T07:21:41.282152+00:00 [queued]>
[2025-08-28T07:30:34.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.sales_per_country manual__2025-08-28T07:21:41.282152+00:00 [queued]>
[2025-08-28T07:30:34.752+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-28T07:30:34.777+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): sales_per_country> on 2025-08-28 07:21:41.282152+00:00
[2025-08-28T07:30:34.785+0000] {standard_task_runner.py:63} INFO - Started process 1436 to run task
[2025-08-28T07:30:34.795+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'sales_per_country', 'manual__2025-08-28T07:21:41.282152+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmptfw9rl1s']
[2025-08-28T07:30:34.799+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask sales_per_country
[2025-08-28T07:30:34.825+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T07:30:34.896+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.sales_per_country manual__2025-08-28T07:21:41.282152+00:00 [running]> on host 9b893e28b5b2
[2025-08-28T07:30:35.153+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='sales_per_country' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T07:21:41.282152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-28T07:21:41.282152+00:00'
[2025-08-28T07:30:35.156+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T07:30:35.209+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-28T07:30:35.221+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'psql -h postgres -U *** -d *** -f /opt/***/sql/sales_per_country.sql']
[2025-08-28T07:30:35.255+0000] {subprocess.py:86} INFO - Output:
[2025-08-28T07:30:35.367+0000] {subprocess.py:93} INFO - Password for user ***:
[2025-08-28T07:30:35.376+0000] {subprocess.py:93} INFO - psql: error: connection to server at "postgres" (172.20.0.2), port 5432 failed: fe_sendauth: no password supplied
[2025-08-28T07:30:35.379+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-28T07:30:35.426+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T07:30:35.456+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-28T07:30:35.474+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_pipeline, task_id=sales_per_country, run_id=manual__2025-08-28T07:21:41.282152+00:00, execution_date=20250828T072141, start_date=20250828T073034, end_date=20250828T073035
[2025-08-28T07:30:35.535+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task sales_per_country (Bash command failed. The command returned a non-zero exit code 2.; 1436)
[2025-08-28T07:30:35.579+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T07:30:35.615+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
