[2025-08-28T07:17:33.560+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T07:17:33.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.daily_sales scheduled__2025-08-27T00:00:00+00:00 [queued]>
[2025-08-28T07:17:33.654+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.daily_sales scheduled__2025-08-27T00:00:00+00:00 [queued]>
[2025-08-28T07:17:33.656+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-08-28T07:17:33.688+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): daily_sales> on 2025-08-27 00:00:00+00:00
[2025-08-28T07:17:33.700+0000] {standard_task_runner.py:63} INFO - Started process 1176 to run task
[2025-08-28T07:17:33.702+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'daily_sales', 'scheduled__2025-08-27T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmpu2bbeiyw']
[2025-08-28T07:17:33.712+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask daily_sales
[2025-08-28T07:17:33.741+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T07:17:33.817+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.daily_sales scheduled__2025-08-27T00:00:00+00:00 [running]> on host 9b893e28b5b2
[2025-08-28T07:17:34.084+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='daily_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-27T00:00:00+00:00'
[2025-08-28T07:17:34.090+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T07:17:34.143+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-28T07:17:34.146+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'psql -h postgres -U *** -d *** -f /opt/***/sql/daily_sales.sql']
[2025-08-28T07:17:34.180+0000] {subprocess.py:86} INFO - Output:
[2025-08-28T07:17:34.285+0000] {subprocess.py:93} INFO - Password for user ***:
[2025-08-28T07:17:34.295+0000] {subprocess.py:93} INFO - psql: error: connection to server at "postgres" (172.20.0.2), port 5432 failed: fe_sendauth: no password supplied
[2025-08-28T07:17:34.297+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-28T07:17:34.298+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T07:17:34.319+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-28T07:17:34.345+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ecommerce_pipeline, task_id=daily_sales, run_id=scheduled__2025-08-27T00:00:00+00:00, execution_date=20250827T000000, start_date=20250828T071733, end_date=20250828T071734
[2025-08-28T07:17:34.384+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task daily_sales (Bash command failed. The command returned a non-zero exit code 2.; 1176)
[2025-08-28T07:17:34.433+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T07:17:34.465+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
