[2025-08-28T07:30:34.685+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T07:30:34.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.top_products manual__2025-08-28T07:21:41.282152+00:00 [queued]>
[2025-08-28T07:30:34.767+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.top_products manual__2025-08-28T07:21:41.282152+00:00 [queued]>
[2025-08-28T07:30:34.769+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-28T07:30:34.795+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): top_products> on 2025-08-28 07:21:41.282152+00:00
[2025-08-28T07:30:34.806+0000] {standard_task_runner.py:63} INFO - Started process 1438 to run task
[2025-08-28T07:30:34.812+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'top_products', 'manual__2025-08-28T07:21:41.282152+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmpibljp8tr']
[2025-08-28T07:30:34.816+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask top_products
[2025-08-28T07:30:34.845+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T07:30:34.913+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.top_products manual__2025-08-28T07:21:41.282152+00:00 [running]> on host 9b893e28b5b2
[2025-08-28T07:30:35.201+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='top_products' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T07:21:41.282152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-28T07:21:41.282152+00:00'
[2025-08-28T07:30:35.203+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T07:30:35.237+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-28T07:30:35.241+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'psql -h postgres -U *** -d *** -f /opt/***/sql/top_products.sql']
[2025-08-28T07:30:35.270+0000] {subprocess.py:86} INFO - Output:
[2025-08-28T07:30:35.366+0000] {subprocess.py:93} INFO - Password for user ***:
[2025-08-28T07:30:35.384+0000] {subprocess.py:93} INFO - psql: error: connection to server at "postgres" (172.20.0.2), port 5432 failed: fe_sendauth: no password supplied
[2025-08-28T07:30:35.420+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-28T07:30:35.445+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T07:30:35.490+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-28T07:30:35.503+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_pipeline, task_id=top_products, run_id=manual__2025-08-28T07:21:41.282152+00:00, execution_date=20250828T072141, start_date=20250828T073034, end_date=20250828T073035
[2025-08-28T07:30:35.536+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 89 for task top_products (Bash command failed. The command returned a non-zero exit code 2.; 1438)
[2025-08-28T07:30:35.570+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T07:30:35.621+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T07:30:35.624+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
