[2025-08-28T06:52:52.893+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T06:52:52.995+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.sales_per_country scheduled__2025-08-27T00:00:00+00:00 [queued]>
[2025-08-28T06:52:53.017+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.sales_per_country scheduled__2025-08-27T00:00:00+00:00 [queued]>
[2025-08-28T06:52:53.018+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-28T06:52:53.050+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): sales_per_country> on 2025-08-27 00:00:00+00:00
[2025-08-28T06:52:53.058+0000] {standard_task_runner.py:63} INFO - Started process 695 to run task
[2025-08-28T06:52:53.071+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'sales_per_country', 'scheduled__2025-08-27T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmpjlm8cuq4']
[2025-08-28T06:52:53.074+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask sales_per_country
[2025-08-28T06:52:53.096+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T06:52:53.176+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.sales_per_country scheduled__2025-08-27T00:00:00+00:00 [running]> on host 9b893e28b5b2
[2025-08-28T06:52:53.402+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='sales_per_country' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-27T00:00:00+00:00'
[2025-08-28T06:52:53.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T06:52:53.429+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-28T06:52:53.432+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'psql -h postgres -U *** -d *** -f /opt/***/sql/sales_per_country.sql']
[2025-08-28T06:52:53.455+0000] {subprocess.py:86} INFO - Output:
[2025-08-28T06:52:53.677+0000] {subprocess.py:93} INFO - Password for user ***:
[2025-08-28T06:52:53.682+0000] {subprocess.py:93} INFO - psql: error: connection to server at "postgres" (172.20.0.2), port 5432 failed: fe_sendauth: no password supplied
[2025-08-28T06:52:53.689+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-28T06:52:53.690+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T06:52:53.708+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-28T06:52:53.717+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_pipeline, task_id=sales_per_country, run_id=scheduled__2025-08-27T00:00:00+00:00, execution_date=20250827T000000, start_date=20250828T065252, end_date=20250828T065253
[2025-08-28T06:52:53.747+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 75 for task sales_per_country (Bash command failed. The command returned a non-zero exit code 2.; 695)
[2025-08-28T06:52:53.809+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T06:52:53.823+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
