[2025-08-27T18:30:53.647+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-27T18:30:53.860+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_online_retail.load_excel_to_postgres manual__2025-08-27T18:30:49.369305+00:00 [queued]>
[2025-08-27T18:30:53.892+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_online_retail.load_excel_to_postgres manual__2025-08-27T18:30:49.369305+00:00 [queued]>
[2025-08-27T18:30:53.898+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-27T18:30:53.972+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_excel_to_postgres> on 2025-08-27 18:30:49.369305+00:00
[2025-08-27T18:30:53.989+0000] {standard_task_runner.py:63} INFO - Started process 490 to run task
[2025-08-27T18:30:54.010+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_online_retail', 'load_excel_to_postgres', 'manual__2025-08-27T18:30:49.369305+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/load_retail_dag.py', '--cfg-path', '/tmp/tmpa2bndnt_']
[2025-08-27T18:30:54.015+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask load_excel_to_postgres
[2025-08-27T18:30:54.078+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-27T18:30:54.231+0000] {task_command.py:426} INFO - Running <TaskInstance: load_online_retail.load_excel_to_postgres manual__2025-08-27T18:30:49.369305+00:00 [running]> on host 13527a2f358f
[2025-08-27T18:30:54.370+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='load_online_retail' AIRFLOW_CTX_TASK_ID='load_excel_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T18:30:49.369305+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-27T18:30:49.369305+00:00'
[2025-08-27T18:30:54.371+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-27T18:30:54.792+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-27T18:30:54.793+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_retail_dag.py", line 11, in run_load_data
    from load_data import main
  File "/opt/airflow/etl/load_data.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-27T18:30:54.813+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=load_online_retail, task_id=load_excel_to_postgres, run_id=manual__2025-08-27T18:30:49.369305+00:00, execution_date=20250827T183049, start_date=20250827T183053, end_date=20250827T183054
[2025-08-27T18:30:54.829+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task load_excel_to_postgres (No module named 'minio'; 490)
[2025-08-27T18:30:54.859+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-27T18:30:54.887+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T18:30:54.889+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
