[2025-08-27T17:53:28.037+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-27T17:53:28.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_online_retail.load_excel_to_postgres manual__2025-08-27T17:51:11.827853+00:00 [queued]>
[2025-08-27T17:53:28.239+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_online_retail.load_excel_to_postgres manual__2025-08-27T17:51:11.827853+00:00 [queued]>
[2025-08-27T17:53:28.243+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-27T17:53:28.322+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_excel_to_postgres> on 2025-08-27 17:51:11.827853+00:00
[2025-08-27T17:53:28.355+0000] {standard_task_runner.py:63} INFO - Started process 295 to run task
[2025-08-27T17:53:28.360+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_online_retail', 'load_excel_to_postgres', 'manual__2025-08-27T17:51:11.827853+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/load_retail_dag.py', '--cfg-path', '/tmp/tmp2vv9skbr']
[2025-08-27T17:53:28.365+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask load_excel_to_postgres
[2025-08-27T17:53:28.459+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-27T17:53:28.631+0000] {task_command.py:426} INFO - Running <TaskInstance: load_online_retail.load_excel_to_postgres manual__2025-08-27T17:51:11.827853+00:00 [running]> on host 13527a2f358f
[2025-08-27T17:53:29.056+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='load_online_retail' AIRFLOW_CTX_TASK_ID='load_excel_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T17:51:11.827853+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-27T17:51:11.827853+00:00'
[2025-08-27T17:53:29.062+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-27T17:53:32.174+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-27T17:53:32.175+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_retail_dag.py", line 7, in run_load_data
    subprocess.run(["python3", "/opt/airflow/etl/load_data.py"], check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/opt/airflow/etl/load_data.py']' returned non-zero exit status 1.
[2025-08-27T17:53:32.201+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=load_online_retail, task_id=load_excel_to_postgres, run_id=manual__2025-08-27T17:51:11.827853+00:00, execution_date=20250827T175111, start_date=20250827T175328, end_date=20250827T175332
[2025-08-27T17:53:32.302+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task load_excel_to_postgres (Command '['python3', '/opt/airflow/etl/load_data.py']' returned non-zero exit status 1.; 295)
[2025-08-27T17:53:32.350+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-27T17:53:32.390+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T17:53:32.427+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
