[2025-08-27T17:30:55.976+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-27T17:30:56.029+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_online_retail.load_excel_to_postgres manual__2025-08-27T17:28:50.657509+00:00 [queued]>
[2025-08-27T17:30:56.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_online_retail.load_excel_to_postgres manual__2025-08-27T17:28:50.657509+00:00 [queued]>
[2025-08-27T17:30:56.050+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-27T17:30:56.090+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_excel_to_postgres> on 2025-08-27 17:28:50.657509+00:00
[2025-08-27T17:30:56.107+0000] {standard_task_runner.py:63} INFO - Started process 365 to run task
[2025-08-27T17:30:56.117+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_online_retail', 'load_excel_to_postgres', 'manual__2025-08-27T17:28:50.657509+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/load_retail_dag.py', '--cfg-path', '/tmp/tmpx3t74qsu']
[2025-08-27T17:30:56.123+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask load_excel_to_postgres
[2025-08-27T17:30:56.151+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-27T17:30:56.202+0000] {task_command.py:426} INFO - Running <TaskInstance: load_online_retail.load_excel_to_postgres manual__2025-08-27T17:28:50.657509+00:00 [running]> on host 231503447b01
[2025-08-27T17:30:56.402+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='load_online_retail' AIRFLOW_CTX_TASK_ID='load_excel_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T17:28:50.657509+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-27T17:28:50.657509+00:00'
[2025-08-27T17:30:56.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-27T17:30:57.754+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-27T17:30:57.755+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_retail_dag.py", line 7, in run_load_data
    subprocess.run(["python3", "/opt/airflow/etl/load_data.py"], check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/opt/airflow/etl/load_data.py']' returned non-zero exit status 1.
[2025-08-27T17:30:57.775+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=load_online_retail, task_id=load_excel_to_postgres, run_id=manual__2025-08-27T17:28:50.657509+00:00, execution_date=20250827T172850, start_date=20250827T173056, end_date=20250827T173057
[2025-08-27T17:30:57.811+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task load_excel_to_postgres (Command '['python3', '/opt/airflow/etl/load_data.py']' returned non-zero exit status 1.; 365)
[2025-08-27T17:30:57.831+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-27T17:30:57.852+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T17:30:57.854+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
